---
title: "case5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
```

```{r}
data("sleepstudy")
head(sleepstudy)
skimr::skim(sleepstudy)
summary(sleepstudy)
```

```{r}
ggplot(sleepstudy, aes(Days, Reaction)) + geom_point() + facet_wrap(~Subject) + geom_smooth(method = "lm", se = FALSE)
```

## Model 1
```{r}
sl_fit <- lmer(Reaction ~ Days + (Days|Subject), data = sleepstudy)

summary(sl_fit)
```

```{r}
N <- nrow(sleepstudy)
subjects <- unique(sleepstudy$Subject)
nsubjects <- length(subjects)

y <- sleepstudy$Reaction
X <- model.matrix(~ Days, data = sleepstudy)
beta <- fixef(sl_fit)
Z <- model.matrix(~ -1 + Subject + Subject:Days, data = sleepstudy)
u <- c(ranef(sl_fit)$Subject[,1], ranef(sl_fit)$Subject[,2])
q <- length(u)

vc <- as.data.frame(VarCorr(sl_fit))
R <- vc$vcov[vc$grp == 'Residual'] * diag(N)
G1 <- vc$vcov[vc$grp == 'Subject'][1] * diag(q/2)
G2 <- vc$vcov[vc$grp == 'Subject'][2] * diag(q/2)
G <- Matrix::bdiag(G1, G2)
G[lower.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]
G[upper.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]

Sigma <- Z %*% G %*% t(Z) + R 
Sigma_inv <- solve(Sigma)

P <- Sigma_inv - Sigma_inv %*% X %*% vcov(sl_fit) %*% t(X) %*% Sigma_inv

varMargRes <- Sigma - X %*% vcov(sl_fit) %*% t(X) 
varCondRes <- R %*% P %*% R  
varU <- G - G %*% t(Z) %*% P %*% Z %*% G

fit_sl <- sleepstudy %>% 
  mutate(fitted = as.vector(X %*% beta),
         resm = y - fitted,
         resc = as.vector(y - fitted - Z %*% u),
         index = 1:n()) %>% 
  rowwise() %>% 
  mutate(resm_std = resm/sqrt(diag(varMargRes)[index]),
         resc_std = resc/sqrt(diag(varCondRes)[index])) %>% 
  ungroup()

sl_unit <- expand_grid(subjects) %>% 
  mutate(Vi = map_dbl(subjects, ~{
    ind <- sleepstudy %>% 
      mutate(index = 1:n()) %>% 
      filter(Subject == .x) %>% 
      pull(index)
    mi <- length(ind)
    Ei <- solve(expm::sqrtm(varMargRes[ind, ind])) %*% fit_sl$resm[ind]
    sqrt(sum((diag(mi) - Ei %*% t(Ei))^2)) / mi
  }),
  Mi = as.vector(t(u) %*% solve(varU) %*% u),
  index = 1:n())
```

### Plot 1
```{r}
ggplot(fit_sl, aes(fitted, resm_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 2
```{r}
ggplot(fit_sl, aes(index, resm_std)) + geom_point() + geom_hline(yintercept = 0)
```

### plot 3
```{r}
ggplot(sl_unit, aes(index, Vi)) + geom_point()
```

### plot 4
```{r}
ggplot(fit_sl, aes(index, resc_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 5
```{r}
ggplot(fit_sl, aes(fitted, resc_std)) + geom_point()
```

### Plot 6
```{r}
ggplot(fit_sl, aes(sample = resc_std)) + geom_qq() + geom_qq_line(color = "red")
```

### Plot 7
```{r}
ggplot(sl_unit, aes(index, Mi)) + geom_point()
```

### Plot 8
```{r}
ggplot(sl_unit, aes(sample = Mi)) + 
  geom_qq(distribution = stats::qchisq, dparams = list(df = q)) +
  geom_qq_line(color = "red",
               distribution = stats::qchisq,
               dparams = list(df = q))
```

### Simulation
```{r simulate}
fit.sim <- simulate(sl_fit, nsim = 19, seed = 1234)
fit.refit <- lapply(fit.sim, refit, object = sl_fit)
fit.simy <- lapply(fit.refit, function(x) getME(x, 'y'))
```

```{r simulate-data}
fit.sim.y <- do.call("cbind", fit.simy)
fit.sim.y <- reshape2::melt(fit.sim.y)[-1]
names(fit.sim.y) <- c(".n", "y")
fit.sim.y$.n <- as.numeric(str_extract(fit.sim.y$.n, "\\d+"))
fit.sim.y$Subject <- rep(sleepstudy$Subject, 19)
fit.sim.y$Days <- rep(sleepstudy$Days, 19)
```

```{r nulldata}
simdat_sl <- purrr::map_dfr(1:19, function(i){
  df <- fit.sim.y %>% filter(.n == i)
  m <- lmer(y ~ Days + (Days|Subject), data = df)
  
  N <- nrow(df)
  subjects <- unique(df$Subject)
  nsubjects <- length(subjects)

  y <- df$y
  X <- model.matrix(~ Days, data = df)
  beta <- fixef(m)
  Z <- model.matrix(~ -1 + Subject + Subject:Days, data = df)
  u <- c(ranef(m)$Subject[,1], ranef(m)$Subject[,2])
  q <- length(u)

  vc <- as.data.frame(VarCorr(m))
  R <- vc$vcov[vc$grp == 'Residual'] * diag(N)
  G1 <- vc$vcov[vc$grp == 'Subject'][1] * diag(q/2)
  G2 <- vc$vcov[vc$grp == 'Subject'][2] * diag(q/2)
  G <- Matrix::bdiag(G1, G2)
  G[lower.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]
  G[upper.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]

  Sigma <- Z %*% G %*% t(Z) + R 
  Sigma_inv <- solve(Sigma)

  P <- Sigma_inv - Sigma_inv %*% X %*% vcov(m) %*% t(X) %*% Sigma_inv

  varMargRes <- Sigma - X %*% vcov(m) %*% t(X) 
  varCondRes <- R %*% P %*% R  
  varU <- G - G %*% t(Z) %*% P %*% Z %*% G
  
  fitted = as.vector(X %*% beta)
  resm = y - fitted
  resc = y - fitted - as.vector(Z %*% u)
  index = 1:nrow(df)
  resm_std = resm / sqrt(diag(varMargRes)[index])
  resc_std = resc / sqrt(diag(varCondRes)[index])
  
  tibble::tibble(df, fitted, resm_std, resc_std, index)
})
```

```{r}
colnames(sleepstudy)[1] <- c('y')
```

#### Plot 1
```{r fig.height=6}
lineup(true = fit_sl, samples = simdat_sl, pos = 9) %>% 
  ggplot(aes(fitted, resm_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 2

```{r fig.height=6}
lineup(true = fit_sl, samples = simdat_sl, pos = 9) %>% 
  ggplot(aes(index, resm_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 4
```{r fig.height=6}
lineup(true = fit_sl, samples = simdat_sl, pos = 9) %>% 
  ggplot(aes(index, resc_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 5
```{r fig.height=6}
lineup(true = fit_sl, samples = simdat_sl, pos = 9) %>% 
  ggplot(aes(fitted, resc_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 6
```{r fig.height=6}
lineup(true = fit_sl, samples = simdat_sl, pos = 9) %>% 
  ggplot(aes(sample = resc_std)) + 
  geom_qq() + geom_qq_line(color = "red") +
  facet_wrap( ~ .sample, ncol=5)
```

##### Least confounded conditional residual
```{r}
R_half <- expm::sqrtm(R)

auxqn <- eigen((R_half %*% P %*% R_half), symmetric = T, only.values = FALSE)

p <- length(beta)

lt <- sqrt(solve(diag((auxqn$values[1:(N-p)])))) %*% t(auxqn$vectors[1:N,1:(N-p)]) %*% solve(expm::sqrtm(R[1:N,1:N]))

var.resmcp <- lt %*% varCondRes[1:N,1:N] %*% t(lt)

resmcp <- (lt %*% fit_sl$resc[1:N] )/sqrt(diag(var.resmcp))

resmcp_sl <- as.data.frame(resmcp)
```
```{r}
ggplot(resmcp_sl, aes(sample = V1)) + geom_qq() + geom_qq_line(color = "red")
```



## Model 2
```{r}
fity <- as.vector(mvtnorm::rmvnorm(1, mean = X %*% beta, sigma = Z %*% G %*% t(Z) + R + rnorm(N, mean = 0, sd = 2), checkSymmetry = FALSE))

sl_df <- tibble(sleepstudy, fity)
sl_df <- sl_df[-1]
head(sl_df)

sl_fit2 <- lmer(fity ~ Days + (Days|Subject), data = sl_df)
summary(sl_fit2)
```

```{r}
N <- nrow(sl_df)
subjects <- unique(sl_df$Subject)
nsubjects <- length(subjects)

y <- sl_df$fity
X <- model.matrix(~ Days, data = sl_df)
beta <- fixef(sl_fit2)
Z <- model.matrix(~ -1 + Subject + Subject:Days, data = sl_df)
u <- c(ranef(sl_fit2)$Subject[,1], ranef(sl_fit2)$Subject[,2])
q <- length(u)

vc <- as.data.frame(VarCorr(sl_fit2))
R <- vc$vcov[vc$grp == 'Residual'] * diag(N)
G1 <- vc$vcov[vc$grp == 'Subject'][1] * diag(q/2)
G2 <- vc$vcov[vc$grp == 'Subject'][2] * diag(q/2)
G <- Matrix::bdiag(G1, G2)
G[lower.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]
G[upper.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]

Sigma <- Z %*% G %*% t(Z) + R 
Sigma_inv <- solve(Sigma)

P <- Sigma_inv - Sigma_inv %*% X %*% vcov(sl_fit2) %*% t(X) %*% Sigma_inv

varMargRes <- Sigma - X %*% vcov(sl_fit2) %*% t(X) 
varCondRes <- R %*% P %*% R  
varU <- G - G %*% t(Z) %*% P %*% Z %*% G

fit_sl2 <- sl_df %>% 
  mutate(fitted = as.vector(X %*% beta),
         resm = y - fitted,
         resc = as.vector(y - fitted - Z %*% u),
         index = 1:n()) %>% 
  rowwise() %>% 
  mutate(resm_std = resm/sqrt(diag(varMargRes)[index]),
         resc_std = resc/sqrt(diag(varCondRes)[index])) %>% 
  ungroup()

unit_sl2 <- expand_grid(subjects) %>% 
  mutate(Vi = map_dbl(subjects, ~{
    ind <- sl_df %>% 
      mutate(index = 1:n()) %>% 
      filter(Subject == .x) %>% 
      pull(index)
    mi <- length(ind)
    Ei <- solve(expm::sqrtm(varMargRes[ind, ind])) %*% fit_sl2$resm[ind]
    sqrt(sum((diag(mi) - Ei %*% t(Ei))^2)) / mi
  }),
  Mi = as.vector(t(u) %*% solve(varU) %*% u),
  index = 1:n())
```

### Plot 1
```{r}
ggplot(fit_sl2, aes(fitted, resm_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 2
```{r}
ggplot(fit_sl2, aes(index, resm_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 3
```{r}
ggplot(unit_sl2, aes(index, Vi)) + geom_point()
```

### Plot 4
```{r}
ggplot(fit_sl2, aes(index, resc_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 5
```{r}
ggplot(fit_sl2, aes(fitted, resc_std)) + geom_point() + geom_hline(yintercept = 0)
```

### Plot 6
```{r}
ggplot(fit_sl2, aes(sample = resc_std)) + geom_qq() + geom_qq_line(color = "red")
```

### Plot 7
```{r}
ggplot(unit_sl2, aes(index, Mi)) + geom_point()
```

### Plot 8

```{r}
ggplot(unit_sl2, aes(sample = Mi)) + 
  geom_qq(distribution = stats::qchisq, dparams = list(df = q)) +
  geom_qq_line(color = "red",
               distribution = stats::qchisq,
               dparams = list(df = q))
```

### Simulation
```{r simulate}
fit.sim <- simulate(sl_fit2, nsim = 19, seed = 1234)
fit.refit <- lapply(fit.sim, refit, object = sl_fit2)
fit.simy <- lapply(fit.refit, function(x) getME(x, 'y'))
```

```{r simulate-data}
fit.sim.y <- do.call("cbind", fit.simy)
fit.sim.y <- reshape2::melt(fit.sim.y)[-1]
names(fit.sim.y) <- c(".n", "y")
fit.sim.y$.n <- as.numeric(str_extract(fit.sim.y$.n, "\\d+"))
fit.sim.y$Subject <- rep(sleepstudy$Subject, 19)
fit.sim.y$Days <- rep(sleepstudy$Days, 19)
```

```{r nulldata}
simdat_sl2 <- purrr::map_dfr(1:19, function(i){
  df <- fit.sim.y %>% filter(.n == i)
  m <- lmer(y ~ Days + (Days|Subject), data = df)
  
  N <- nrow(df)
  subjects <- unique(df$Subject)
  nsubjects <- length(subjects)

  y <- df$y
  X <- model.matrix(~ Days, data = df)
  beta <- fixef(m)
  Z <- model.matrix(~ -1 + Subject + Subject:Days, data = df)
  u <- c(ranef(m)$Subject[,1], ranef(m)$Subject[,2])
  q <- length(u)

  vc <- as.data.frame(VarCorr(m))
  R <- vc$vcov[vc$grp == 'Residual'] * diag(N)
  G1 <- vc$vcov[vc$grp == 'Subject'][1] * diag(q/2)
  G2 <- vc$vcov[vc$grp == 'Subject'][2] * diag(q/2)
  G <- Matrix::bdiag(G1, G2)
  G[lower.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]
  G[upper.tri(G)] <- vc$vcov[vc$grp == 'Subject'][3]

  Sigma <- Z %*% G %*% t(Z) + R 
  Sigma_inv <- solve(Sigma)

  P <- Sigma_inv - Sigma_inv %*% X %*% vcov(m) %*% t(X) %*% Sigma_inv

  varMargRes <- Sigma - X %*% vcov(m) %*% t(X) 
  varCondRes <- R %*% P %*% R  
  varU <- G - G %*% t(Z) %*% P %*% Z %*% G
  
  fitted = as.vector(X %*% beta)
  resm = y - fitted
  resc = y - fitted - as.vector(Z %*% u)
  index = 1:nrow(df)
  resm_std = resm / sqrt(diag(varMargRes)[index])
  resc_std = resc / sqrt(diag(varCondRes)[index])
  
  tibble::tibble(df, fitted, resm_std, resc_std, index)
})
```

#### Plot 1
```{r fig.height=6}
lineup(true = fit_sl2, samples = simdat_sl2, pos = 9) %>% 
  ggplot(aes(fitted, resm_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 2
```{r fig.height=6}
lineup(true = fit_sl2, samples = simdat_sl2, pos = 9) %>% 
  ggplot(aes(index, resm_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 4
```{r fig.height=6}
lineup(true = fit_sl2, samples = simdat_sl2, pos = 9) %>% 
  ggplot(aes(index, resc_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 5
```{r fig.height=6}
lineup(true = fit_sl2, samples = simdat_sl2, pos = 9) %>% 
  ggplot(aes(fitted, resc_std)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  facet_wrap( ~ .sample, ncol=5)
```

#### Plot 6
```{r fig.height=6}
lineup(true = fit_sl2, samples = simdat_sl2, pos = 9) %>% 
  ggplot(aes(sample = resc_std)) + 
  geom_qq() + 
  geom_qq_line(color = "red") +
  facet_wrap( ~ .sample, ncol=5)
```

##### Least confounded conditional residual
```{r}
R_half <- expm::sqrtm(R)

auxqn <- eigen((R_half %*% P %*% R_half), symmetric = T, only.values = FALSE)

p <- length(beta)

lt <- sqrt(solve(diag((auxqn$values[1:(N-p)])))) %*% t(auxqn$vectors[1:N,1:(N-p)]) %*% solve(expm::sqrtm(R[1:N,1:N]))

var.resmcp <- lt %*% varCondRes[1:N,1:N] %*% t(lt)

resmcp <- (lt %*% fit_sl2$resc[1:N] )/sqrt(diag(var.resmcp))

resmcp_sl2 <- as.data.frame(resmcp)
```

```{r}
ggplot(resmcp_sl2, aes(sample = V1)) + geom_qq() + geom_qq_line(color = "red")
```

## Model 3

Since `lmer()` function fits the model with the residuals which is heteroscedasticity and autocorrelation.
```{r}
sl_fit3 <- lmer(y ~ Days + (Days||Subject), data = sleepstudy)

summary(sl_fit3)
```















